# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Download and Install Swift
        run: |
          SWIFT_VERSION=6.0
          wget https://swift.org/builds/swift-${SWIFT_VERSION}-release/macosx/swift-${SWIFT_VERSION}-RELEASE/swift-${SWIFT_VERSION}-RELEASE-macosx.tar.gz
          tar xzf swift-${SWIFT_VERSION}-RELEASE-macosx.tar.gz
          sudo mv swift-${SWIFT_VERSION}-RELEASE-macosx /usr/local/swift
          echo 'export PATH=/usr/local/swift/usr/bin:$PATH' >> $GITHUB_ENV
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v

